<a href="https://colab.research.google.com/github/kartik580/uber-ola-numerical-data-analysis-project/blob/main/uber_ola_num_data_analysis_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## uber data analysis(numerical)
- user_id
- rider_id
- experience
- rating
- total_trip_time
- no_of_trip
- distance_travelled
- vehicle_type(2-bike,3-auto,4-car)


In [101]:
import numpy as np

In [102]:
user_id=np.arange(1,26)
print(user_id)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [103]:
rider_id=np.arange(101,126)
print(rider_id)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125]


In [104]:
experience=np.random.randint(1,18,25)
print(experience)

[15  3  5  6  6 16  4 11  3 15 13  4 14 15  9 10 10  9 14  3 10 12  4  1
  9]


In [105]:
rating= np.random.randint(1,6,25)
print(rating)

[5 3 1 1 2 4 2 5 2 1 3 3 4 5 2 4 2 5 4 4 3 3 1 1 5]


In [106]:
total_trip_time=np.random.randint(0,745,25)
print(total_trip_time)

[186 244 542 294 698 184 645 287 381 235 161 359  81 590 382 400 254 520
 207 240 483 301 725  66 554]


In [107]:
no_of_trip= np.random.randint(15,451,25)
print(no_of_trip)

[409 398 129  89 261 282 406  18  74 137 176  85 147  42 435 105  45 281
 173 434 163 109 310 221  39]


In [108]:
distance_travelled=np.random.randint(15,12000,25)
print(distance_travelled)

[  406 10042 11023  6260  8477 11809  5881 11128  9743  2483   533  6131
  4193  3932  5504  7814 11966  1917  5967  8214  7616  3357  1334  7348
  5321]


In [109]:
vehicle_type=np.random.randint(2,5,25)
print(vehicle_type)

[2 2 3 4 4 4 4 3 2 3 3 3 2 3 2 2 3 3 3 2 2 4 2 4 2]


In [110]:
# np.concatenate
# np.column_stack
# np.stack

In [111]:
data={
    "user_id": user_id
}
arr=np.array(list(data.values()))
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


In [112]:
user_id = np.arange(1, 26)
rider_id = np.arange(101, 126)
experience=np.random.randint(1,18,25)
rating= np.random.randint(1,6,25)
total_trip_time=np.random.randint(0,745,25)
no_of_trip= np.random.randint(15,451,25)
distance_travelled=np.random.randint(15,12000,25)
vehicle_type=np.random.randint(2,5,25)

uber_data = np.concatenate((user_id.reshape(-1,1),
                        rider_id.reshape(-1,1),
                        experience.reshape(-1,1),
                        rating.reshape(-1,1),
                        total_trip_time.reshape(-1,1),
                        no_of_trip.reshape(-1,1),
                        distance_travelled.reshape(-1,1),
                        vehicle_type.reshape(-1,1)),axis=1)

print(uber_data)



[[    1   101     8     5   175   191 10674     2]
 [    2   102    13     3   278   371  8649     2]
 [    3   103     2     1    64   193 10286     2]
 [    4   104     3     5   709   168  9720     4]
 [    5   105     6     3   390   222  8255     2]
 [    6   106    17     5   137   184  5750     2]
 [    7   107     6     2   743    18  1454     2]
 [    8   108     3     4   423   132  8236     3]
 [    9   109     8     4   588   211  9179     4]
 [   10   110     1     3   556   449  3804     4]
 [   11   111    10     3   241   209  9485     4]
 [   12   112     4     5   504   311   840     2]
 [   13   113    10     1   286   120  1428     3]
 [   14   114     5     3   656   430   444     2]
 [   15   115     1     3    19   319  4752     3]
 [   16   116     4     1   632    52  2854     2]
 [   17   117    12     5   221    97  2987     4]
 [   18   118     6     5   449   264  7051     3]
 [   19   119    17     2   317    17  6687     2]
 [   20   120     7     2   431

In [113]:
data=np.column_stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data)

[[    1   101     8     5   175   191 10674     2]
 [    2   102    13     3   278   371  8649     2]
 [    3   103     2     1    64   193 10286     2]
 [    4   104     3     5   709   168  9720     4]
 [    5   105     6     3   390   222  8255     2]
 [    6   106    17     5   137   184  5750     2]
 [    7   107     6     2   743    18  1454     2]
 [    8   108     3     4   423   132  8236     3]
 [    9   109     8     4   588   211  9179     4]
 [   10   110     1     3   556   449  3804     4]
 [   11   111    10     3   241   209  9485     4]
 [   12   112     4     5   504   311   840     2]
 [   13   113    10     1   286   120  1428     3]
 [   14   114     5     3   656   430   444     2]
 [   15   115     1     3    19   319  4752     3]
 [   16   116     4     1   632    52  2854     2]
 [   17   117    12     5   221    97  2987     4]
 [   18   118     6     5   449   264  7051     3]
 [   19   119    17     2   317    17  6687     2]
 [   20   120     7     2   431

In [114]:
data.ndim

2

In [115]:
data.shape

(25, 8)

In [116]:
data.dtype

dtype('int64')

In [117]:
data.itemsize

8

In [118]:
data.size

200

In [119]:
data1=np.concatenate([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data1)

[    1     2     3     4     5     6     7     8     9    10    11    12
    13    14    15    16    17    18    19    20    21    22    23    24
    25   101   102   103   104   105   106   107   108   109   110   111
   112   113   114   115   116   117   118   119   120   121   122   123
   124   125     8    13     2     3     6    17     6     3     8     1
    10     4    10     5     1     4    12     6    17     7     2    16
    10     7     3     5     3     1     5     3     5     2     4     4
     3     3     5     1     3     3     1     5     5     2     2     2
     1     4     4     2   175   278    64   709   390   137   743   423
   588   556   241   504   286   656    19   632   221   449   317   431
   524    46   659   198   670   191   371   193   168   222   184    18
   132   211   449   209   311   120   430   319    52    97   264    17
   417   223   266   342   295   413 10674  8649 10286  9720  8255  5750
  1454  8236  9179  3804  9485   840  1428   444  4

In [120]:
data1.ndim

1

In [121]:
data1.shape

(200,)

In [122]:
data1.size

200

In [123]:
data1.itemsize

8

In [124]:
data1.dtype

dtype('int64')

In [125]:
data2=np.stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data2)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25]
 [  101   102   103   104   105   106   107   108   109   110   111   112
    113   114   115   116   117   118   119   120   121   122   123   124
    125]
 [    8    13     2     3     6    17     6     3     8     1    10     4
     10     5     1     4    12     6    17     7     2    16    10     7
      3]
 [    5     3     1     5     3     5     2     4     4     3     3     5
      1     3     3     1     5     5     2     2     2     1     4     4
      2]
 [  175   278    64   709   390   137   743   423   588   556   241   504
    286   656    19   632   221   449   317   431   524    46   659   198
    670]
 [  191   371   193   168   222   184    18   132   211   449   209   311
    120   430   319    52    97   264    17   417   223   266   342   295
    413]
 [10674  8649 10286  9720  8255  5750  1454  8236  9179  3

In [126]:
data2.ndim

2

In [127]:
data2.shape

(8, 25)

In [128]:
data2.dtype

dtype('int64')

In [129]:
data2.size

200

In [130]:
data=np.stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type],axis=0)
print(data)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25]
 [  101   102   103   104   105   106   107   108   109   110   111   112
    113   114   115   116   117   118   119   120   121   122   123   124
    125]
 [    8    13     2     3     6    17     6     3     8     1    10     4
     10     5     1     4    12     6    17     7     2    16    10     7
      3]
 [    5     3     1     5     3     5     2     4     4     3     3     5
      1     3     3     1     5     5     2     2     2     1     4     4
      2]
 [  175   278    64   709   390   137   743   423   588   556   241   504
    286   656    19   632   221   449   317   431   524    46   659   198
    670]
 [  191   371   193   168   222   184    18   132   211   449   209   311
    120   430   319    52    97   264    17   417   223   266   342   295
    413]
 [10674  8649 10286  9720  8255  5750  1454  8236  9179  3

In [131]:
data.shape

(8, 25)

In [132]:

data=np.stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type],axis=1)
print(data)

[[    1   101     8     5   175   191 10674     2]
 [    2   102    13     3   278   371  8649     2]
 [    3   103     2     1    64   193 10286     2]
 [    4   104     3     5   709   168  9720     4]
 [    5   105     6     3   390   222  8255     2]
 [    6   106    17     5   137   184  5750     2]
 [    7   107     6     2   743    18  1454     2]
 [    8   108     3     4   423   132  8236     3]
 [    9   109     8     4   588   211  9179     4]
 [   10   110     1     3   556   449  3804     4]
 [   11   111    10     3   241   209  9485     4]
 [   12   112     4     5   504   311   840     2]
 [   13   113    10     1   286   120  1428     3]
 [   14   114     5     3   656   430   444     2]
 [   15   115     1     3    19   319  4752     3]
 [   16   116     4     1   632    52  2854     2]
 [   17   117    12     5   221    97  2987     4]
 [   18   118     6     5   449   264  7051     3]
 [   19   119    17     2   317    17  6687     2]
 [   20   120     7     2   431

In [133]:
data.shape

(25, 8)

In [134]:
data=np.hstack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data)

[    1     2     3     4     5     6     7     8     9    10    11    12
    13    14    15    16    17    18    19    20    21    22    23    24
    25   101   102   103   104   105   106   107   108   109   110   111
   112   113   114   115   116   117   118   119   120   121   122   123
   124   125     8    13     2     3     6    17     6     3     8     1
    10     4    10     5     1     4    12     6    17     7     2    16
    10     7     3     5     3     1     5     3     5     2     4     4
     3     3     5     1     3     3     1     5     5     2     2     2
     1     4     4     2   175   278    64   709   390   137   743   423
   588   556   241   504   286   656    19   632   221   449   317   431
   524    46   659   198   670   191   371   193   168   222   184    18
   132   211   449   209   311   120   430   319    52    97   264    17
   417   223   266   342   295   413 10674  8649 10286  9720  8255  5750
  1454  8236  9179  3804  9485   840  1428   444  4

In [135]:
data.shape

(200,)

In [136]:
data=np.vstack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25]
 [  101   102   103   104   105   106   107   108   109   110   111   112
    113   114   115   116   117   118   119   120   121   122   123   124
    125]
 [    8    13     2     3     6    17     6     3     8     1    10     4
     10     5     1     4    12     6    17     7     2    16    10     7
      3]
 [    5     3     1     5     3     5     2     4     4     3     3     5
      1     3     3     1     5     5     2     2     2     1     4     4
      2]
 [  175   278    64   709   390   137   743   423   588   556   241   504
    286   656    19   632   221   449   317   431   524    46   659   198
    670]
 [  191   371   193   168   222   184    18   132   211   449   209   311
    120   430   319    52    97   264    17   417   223   266   342   295
    413]
 [10674  8649 10286  9720  8255  5750  1454  8236  9179  3

In [137]:
data.shape

(8, 25)

In [138]:
data=np.row_stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25]
 [  101   102   103   104   105   106   107   108   109   110   111   112
    113   114   115   116   117   118   119   120   121   122   123   124
    125]
 [    8    13     2     3     6    17     6     3     8     1    10     4
     10     5     1     4    12     6    17     7     2    16    10     7
      3]
 [    5     3     1     5     3     5     2     4     4     3     3     5
      1     3     3     1     5     5     2     2     2     1     4     4
      2]
 [  175   278    64   709   390   137   743   423   588   556   241   504
    286   656    19   632   221   449   317   431   524    46   659   198
    670]
 [  191   371   193   168   222   184    18   132   211   449   209   311
    120   430   319    52    97   264    17   417   223   266   342   295
    413]
 [10674  8649 10286  9720  8255  5750  1454  8236  9179  3

/tmp/ipykernel_1088/2196302568.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  data=np.row_stack([user_id,


In [139]:
data[2>4]

array([], shape=(0, 8, 25), dtype=int64)

In [140]:
data=np.column_stack([user_id,
                      rider_id,
                      experience,
                      rating,
                      total_trip_time,
                      no_of_trip,
                      distance_travelled,
                      vehicle_type])
print(data)

[[    1   101     8     5   175   191 10674     2]
 [    2   102    13     3   278   371  8649     2]
 [    3   103     2     1    64   193 10286     2]
 [    4   104     3     5   709   168  9720     4]
 [    5   105     6     3   390   222  8255     2]
 [    6   106    17     5   137   184  5750     2]
 [    7   107     6     2   743    18  1454     2]
 [    8   108     3     4   423   132  8236     3]
 [    9   109     8     4   588   211  9179     4]
 [   10   110     1     3   556   449  3804     4]
 [   11   111    10     3   241   209  9485     4]
 [   12   112     4     5   504   311   840     2]
 [   13   113    10     1   286   120  1428     3]
 [   14   114     5     3   656   430   444     2]
 [   15   115     1     3    19   319  4752     3]
 [   16   116     4     1   632    52  2854     2]
 [   17   117    12     5   221    97  2987     4]
 [   18   118     6     5   449   264  7051     3]
 [   19   119    17     2   317    17  6687     2]
 [   20   120     7     2   431

In [141]:
##total rows
print(data.shape[0])

25


In [142]:
#total features
print(data[3][5])

168


In [143]:
print(data[3:11])

[[   4  104    3    5  709  168 9720    4]
 [   5  105    6    3  390  222 8255    2]
 [   6  106   17    5  137  184 5750    2]
 [   7  107    6    2  743   18 1454    2]
 [   8  108    3    4  423  132 8236    3]
 [   9  109    8    4  588  211 9179    4]
 [  10  110    1    3  556  449 3804    4]
 [  11  111   10    3  241  209 9485    4]]


In [144]:
print(data[::2])

[[    1   101     8     5   175   191 10674     2]
 [    3   103     2     1    64   193 10286     2]
 [    5   105     6     3   390   222  8255     2]
 [    7   107     6     2   743    18  1454     2]
 [    9   109     8     4   588   211  9179     4]
 [   11   111    10     3   241   209  9485     4]
 [   13   113    10     1   286   120  1428     3]
 [   15   115     1     3    19   319  4752     3]
 [   17   117    12     5   221    97  2987     4]
 [   19   119    17     2   317    17  6687     2]
 [   21   121     2     2   524   223  5759     2]
 [   23   123    10     4   659   342  7339     2]
 [   25   125     3     2   670   413 10173     2]]


In [145]:
print(data[1::2])

[[    2   102    13     3   278   371  8649     2]
 [    4   104     3     5   709   168  9720     4]
 [    6   106    17     5   137   184  5750     2]
 [    8   108     3     4   423   132  8236     3]
 [   10   110     1     3   556   449  3804     4]
 [   12   112     4     5   504   311   840     2]
 [   14   114     5     3   656   430   444     2]
 [   16   116     4     1   632    52  2854     2]
 [   18   118     6     5   449   264  7051     3]
 [   20   120     7     2   431   417  8575     2]
 [   22   122    16     1    46   266  7419     4]
 [   24   124     7     4   198   295 10379     3]]


In [146]:
data[[5],[4]]

array([137])

In [147]:
print(data[::,3]>=5)


[ True False False  True False  True False False False False False  True
 False False False False  True  True False False False False False False
 False]


In [148]:
print(data[::,::2])

[[    1     8   175 10674]
 [    2    13   278  8649]
 [    3     2    64 10286]
 [    4     3   709  9720]
 [    5     6   390  8255]
 [    6    17   137  5750]
 [    7     6   743  1454]
 [    8     3   423  8236]
 [    9     8   588  9179]
 [   10     1   556  3804]
 [   11    10   241  9485]
 [   12     4   504   840]
 [   13    10   286  1428]
 [   14     5   656   444]
 [   15     1    19  4752]
 [   16     4   632  2854]
 [   17    12   221  2987]
 [   18     6   449  7051]
 [   19    17   317  6687]
 [   20     7   431  8575]
 [   21     2   524  5759]
 [   22    16    46  7419]
 [   23    10   659  7339]
 [   24     7   198 10379]
 [   25     3   670 10173]]


In [149]:
print(data[::,1::2])

[[101   5 191   2]
 [102   3 371   2]
 [103   1 193   2]
 [104   5 168   4]
 [105   3 222   2]
 [106   5 184   2]
 [107   2  18   2]
 [108   4 132   3]
 [109   4 211   4]
 [110   3 449   4]
 [111   3 209   4]
 [112   5 311   2]
 [113   1 120   3]
 [114   3 430   2]
 [115   3 319   3]
 [116   1  52   2]
 [117   5  97   4]
 [118   5 264   3]
 [119   2  17   2]
 [120   2 417   2]
 [121   2 223   2]
 [122   1 266   4]
 [123   4 342   2]
 [124   4 295   3]
 [125   2 413   2]]


In [150]:
print(data[:,[1,3,4,5]])

[[101   5 175 191]
 [102   3 278 371]
 [103   1  64 193]
 [104   5 709 168]
 [105   3 390 222]
 [106   5 137 184]
 [107   2 743  18]
 [108   4 423 132]
 [109   4 588 211]
 [110   3 556 449]
 [111   3 241 209]
 [112   5 504 311]
 [113   1 286 120]
 [114   3 656 430]
 [115   3  19 319]
 [116   1 632  52]
 [117   5 221  97]
 [118   5 449 264]
 [119   2 317  17]
 [120   2 431 417]
 [121   2 524 223]
 [122   1  46 266]
 [123   4 659 342]
 [124   4 198 295]
 [125   2 670 413]]
